import LinkButton from '../components/LinkButton'
import MediaPlaceholder from '../components/MediaPlaceholder'
import { useLanguage } from '../i18n/useLanguage.js'

// A página de detalhes é orientada pelos campos do item. A distinção entre
// e-book e aplicativo fica concentrada aqui, evitando condicionais espalhadas.
export default function Detail({ item, onBack, onFeedback }) {
  const { t } = useLanguage()
  const isBook = item.type === 'ebook'
  const fields = isBook ? [['Autor', item.author], ['Categoria', item.category], ['Páginas', item.pages], ['Formato', item.format], ['ISBN', item.isbn], ['Editora', item.publisher]] : [['Categoria', item.category], ['Plataforma', item.platform], ['Status', item.status], ['Versão', item.version], ['Tamanho', item.size], ['Atualização', item.updatedAt]]
  return <main className="detail-page"><button className="back-button" onClick={onBack}>← {t('back')}</button><div className="detail-top"><MediaPlaceholder item={item} large /><div className="detail-intro">{item.status === 'Em construção' && <div className="construction-banner detail-banner">{t('statusBuilding')}</div>}<span className="eyebrow">{isBook ? t('ebookLabel') : item.type === 'game' ? t('gameLabel') : t('appLabel')}</span><h1>{item.name || item.title}</h1><p className="lead">{isBook ? item.author : item.description || t('pendingDescription')}</p><div className="detail-actions"><LinkButton href={isBook ? item.purchaseLink : item.download}>{isBook ? t('buy') : t('download')} <span>↗</span></LinkButton>{!isBook && <LinkButton href={item.googlePlay}>Google Play</LinkButton>}{isBook && <LinkButton href={item.sample}>{t('sample')}</LinkButton>}<button className="button quiet" onClick={onFeedback}>{t('share')} ↗</button></div></div></div><div className="detail-body"><div><h2>{isBook ? t('synopsis') : t('aboutProject')}</h2><p>{isBook ? item.synopsis : item.fullDescription || t('unavailable')}</p></div><aside><h3>{t('information')}</h3>{fields.map(([label, value]) => <div className="info-row" key={label}><span>{label}</span><strong>{value || t('pending')}</strong></div>)}</aside></div>{!isBook && <div className="screenshots"><h2>{t('screenshots')}</h2><div className="screenshot-row">{item.screenshots.length ? item.screenshots.map((image) => <img key={image} src={image} alt={`Tela de ${item.name}`} />) : <div className="screenshot-empty">{t('screenshotsPending')}</div>}</div></div>}</main>
}
