import LinkButton from '../components/LinkButton'
import MediaPlaceholder from '../components/MediaPlaceholder'

// A página de detalhes é orientada pelos campos do item. A distinção entre
// e-book e aplicativo fica concentrada aqui, evitando condicionais espalhadas.
export default function Detail({ item, onBack }) {
  const isBook = item.type === 'ebook'
  const fields = isBook ? [['Autor', item.author], ['Categoria', item.category], ['Páginas', item.pages], ['Formato', item.format], ['ISBN', item.isbn], ['Editora', item.publisher]] : [['Categoria', item.category], ['Plataforma', item.platform], ['Status', item.status], ['Versão', item.version], ['Tamanho', item.size], ['Atualização', item.updatedAt]]
  return <main className="detail-page"><button className="back-button" onClick={onBack}>← Voltar ao catálogo</button><div className="detail-top"><MediaPlaceholder item={item} large /><div className="detail-intro">{item.status === 'Em construção' && <div className="construction-banner detail-banner">Em construção</div>}<span className="eyebrow">{isBook ? 'E-BOOK' : item.type === 'game' ? 'JOGO' : 'APLICATIVO'}</span><h1>{item.name || item.title}</h1><p className="lead">{isBook ? item.author : item.description || 'Descrição pendente'}</p><div className="detail-actions"><LinkButton href={isBook ? item.purchaseLink : item.download}>{isBook ? 'Comprar e-book' : 'Baixar projeto'} <span>↗</span></LinkButton>{!isBook && <LinkButton href={item.googlePlay}>Google Play</LinkButton>}{isBook && <LinkButton href={item.sample}>Ler amostra</LinkButton>}</div></div></div><div className="detail-body"><div><h2>{isBook ? 'Sinopse' : 'Sobre o projeto'}</h2><p>{isBook ? item.synopsis : item.fullDescription || 'As informações detalhadas deste projeto ainda não foram cadastradas.'}</p></div><aside><h3>Informações</h3>{fields.map(([label, value]) => <div className="info-row" key={label}><span>{label}</span><strong>{value || 'Pendente'}</strong></div>)}</aside></div>{!isBook && <div className="screenshots"><h2>Imagens do projeto</h2><div className="screenshot-row">{item.screenshots.length ? item.screenshots.map((image) => <img key={image} src={image} alt={`Tela de ${item.name}`} />) : <div className="screenshot-empty">Screenshots ainda não cadastrados</div>}</div></div>}</main>
}
