import { useEffect, useState } from 'react'
import { apps } from './data/apps'
import { ebooks } from './data/ebooks'
import { categories } from './data/categories'
import './App.css'

const allItems = [...apps, ...ebooks]
const text = (item) => item.name || item.title

function Placeholder({ item, large = false }) {
  const image = item.icon || item.cover
  return image ? <img className={large ? 'item-art large' : 'item-art'} src={image} alt={text(item)} /> : <div className={`placeholder ${large ? 'large' : ''}`} aria-label={`Imagem pendente de ${text(item)}`}><span>{text(item).slice(0, 1)}</span></div>
}
function EmptyLink({ href, children }) { return href ? <a className="button secondary" href={href} target="_blank" rel="noreferrer">{children}</a> : <span className="button disabled">Link pendente</span> }
function AppCard({ item, onOpen }) { return <article className="product-card">{item.status === 'Em construção' && <div className="construction-banner">Em construção</div>}<Placeholder item={item} /><div className="product-copy"><span className="eyebrow">{item.type === 'game' ? 'Jogo' : 'Aplicativo'}</span><h3>{text(item)}</h3><p>{item.description || 'Descrição pendente'}</p><div className="card-meta"><span>{item.category || 'Categoria pendente'}</span><span>{item.platform || 'Plataforma pendente'}</span></div><button className="text-button" onClick={() => onOpen(item)}>Ver detalhes <span aria-hidden="true">↗</span></button></div></article> }
function EbookCard({ item, onOpen }) { return <article className="product-card ebook-card"><Placeholder item={item} /><div className="product-copy"><span className="eyebrow">E-book</span><h3>{text(item)}</h3><p>{item.author}</p><div className="card-meta"><span>{item.category || 'Categoria pendente'}</span><span>Digital</span></div><button className="text-button" onClick={() => onOpen(item)}>Ler detalhes <span aria-hidden="true">↗</span></button></div></article> }
function Header({ query, setQuery, theme, setTheme, onNavigate }) { return <header className="site-header"><a className="brand" href="#/" onClick={() => onNavigate('home')}><span className="brand-mark">N</span><span>Nando<span className="brand-accent">Store</span></span></a><nav className="main-nav" aria-label="Navegação principal"><button onClick={() => onNavigate('home')}>Início</button><button onClick={() => onNavigate('apps')}>Aplicativos</button><button onClick={() => onNavigate('ebooks')}>E-books</button><button onClick={() => onNavigate('about')}>Sobre</button></nav><div className="header-actions"><label className="search"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar no catálogo" aria-label="Pesquisar no catálogo" /></label><button className="theme-toggle" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label="Alternar tema">{theme === 'light' ? '☾' : '☀'}</button></div></header> }
function Section({ title, kicker, children, action }) { return <section className="content-section"><div className="section-heading"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2></div>{action}</div>{children}</section> }
function SearchResults({ query, onOpen }) { const results = allItems.filter((item) => Object.values(item).join(' ').toLowerCase().includes(query.toLowerCase())); return <Section title={`Resultados para “${query}”`} kicker="Pesquisa"><div className="product-grid">{results.length ? results.map((item) => item.type === 'ebook' ? <EbookCard key={item.id} item={item} onOpen={onOpen} /> : <AppCard key={item.id} item={item} onOpen={onOpen} />) : <div className="empty-state"><span>⌕</span><h3>Nada encontrado ainda</h3><p>Tente buscar por outro nome ou categoria.</p></div>}</div></Section> }
function Home({ onOpen, onNavigate, query }) { const recent = apps.slice(0, 4); return <main><section className="hero"><div className="hero-copy"><span className="eyebrow">PORTAL DE PROJETOS</span><h1>Ideias que ganham <em>vida.</em></h1><p>Um espaço para descobrir aplicativos, jogos e leituras criados por PB. Fernando Saldanha.</p><div className="hero-actions"><button className="button primary" onClick={() => onNavigate('apps')}>Explorar aplicativos <span>↗</span></button><button className="button quiet" onClick={() => onNavigate('ebooks')}>Conhecer os e-books</button></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-card back"><span>06</span><small>PROJETOS</small></div><div className="hero-card front"><span>01</span><small>LEITURA</small><strong>Gatilhos<br />do pecado</strong></div></div></section>{query && <SearchResults query={query} onOpen={onOpen} />}{!query && <><Section title="Em destaque" kicker="Seleção editorial"><div className="featured-grid">{apps.filter((item) => item.featured).slice(0, 3).map((item) => <AppCard key={item.id} item={item} onOpen={onOpen} />)}</div></Section><Section title="Mais recentes" kicker="Catálogo"><div className="product-grid">{recent.map((item) => <AppCard key={item.id} item={item} onOpen={onOpen} />)}</div></Section><section className="split-banner"><div><span className="eyebrow">EM BREVE</span><h2>Uma biblioteca para<br /><em>pausar e pensar.</em></h2></div><div className="banner-book"><span>G</span><strong>Gatilhos<br />do pecado</strong><small>PB. Fernando Saldanha</small></div><button className="button light" onClick={() => onOpen(ebooks[0])}>Ver e-book <span>↗</span></button></section><Section title="Meus projetos" kicker="Universo NandoStore" action={<button className="text-button" onClick={() => onNavigate('apps')}>Ver catálogo completo ↗</button>}><div className="project-strip">{apps.map((item, index) => <button key={item.id} className="project-chip" onClick={() => onOpen(item)}><span className={`mini-symbol symbol-${index % 4}`}>{text(item).slice(0, 1)}</span><span>{text(item)}</span></button>)}</div></Section></>}</main> }
function Catalog({ type, onOpen }) { const [filter, setFilter] = useState('all'); const list = type === 'ebooks' ? ebooks : apps.filter((item) => filter === 'all' || item.type === filter); return <main className="catalog-page"><div className="page-intro"><span className="eyebrow">{type === 'ebooks' ? 'LEITURAS' : 'PROJETOS'}</span><h1>{type === 'ebooks' ? 'E-books' : 'Aplicativos e jogos'}</h1><p>{type === 'ebooks' ? 'Leituras para acompanhar ideias que ficam.' : 'Conheça os projetos e acompanhe o que está sendo construído.'}</p></div>{type !== 'ebooks' && <div className="filter-row">{categories.map((category) => <button className={filter === category.id ? 'filter active' : 'filter'} key={category.id} onClick={() => setFilter(category.id)}>{category.label}</button>)}</div>}<div className="product-grid catalog-grid">{list.map((item) => type === 'ebooks' ? <EbookCard key={item.id} item={item} onOpen={onOpen} /> : <AppCard key={item.id} item={item} onOpen={onOpen} />)}</div></main> }
function Detail({ item, onBack }) { const isBook = item.type === 'ebook'; const fields = isBook ? [['Autor', item.author], ['Categoria', item.category], ['Páginas', item.pages], ['Formato', item.format], ['ISBN', item.isbn], ['Editora', item.publisher]] : [['Categoria', item.category], ['Plataforma', item.platform], ['Status', item.status], ['Versão', item.version], ['Tamanho', item.size], ['Atualização', item.updatedAt]]; return <main className="detail-page"><button className="back-button" onClick={onBack}>← Voltar ao catálogo</button><div className="detail-top"><Placeholder item={item} large /><div className="detail-intro">{item.status === 'Em construção' && <div className="construction-banner detail-banner">Em construção</div>}<span className="eyebrow">{isBook ? 'E-BOOK' : item.type === 'game' ? 'JOGO' : 'APLICATIVO'}</span><h1>{text(item)}</h1><p className="lead">{isBook ? item.author : item.description || 'Descrição pendente'}</p><div className="detail-actions"><EmptyLink href={isBook ? item.purchaseLink : item.download}>{isBook ? 'Comprar e-book' : 'Baixar projeto'} <span>↗</span></EmptyLink>{!isBook && <EmptyLink href={item.googlePlay}>Google Play</EmptyLink>}{isBook && <EmptyLink href={item.sample}>Ler amostra</EmptyLink>}</div></div></div><div className="detail-body"><div><h2>{isBook ? 'Sinopse' : 'Sobre o projeto'}</h2><p>{isBook ? item.synopsis : item.fullDescription || 'As informações detalhadas deste projeto ainda não foram cadastradas.'}</p></div><aside><h3>Informações</h3>{fields.map(([label, value]) => <div className="info-row" key={label}><span>{label}</span><strong>{value || 'Pendente'}</strong></div>)}</aside></div>{!isBook && <div className="screenshots"><h2>Imagens do projeto</h2><div className="screenshot-row">{item.screenshots.length ? item.screenshots.map((image) => <img key={image} src={image} alt={`Tela de ${item.name}`} />) : <div className="screenshot-empty">Screenshots ainda não cadastrados</div>}</div></div>}</main> }
function About() { return <main className="about-page"><span className="eyebrow">O AUTOR</span><h1>PB. Fernando<br /><em>Saldanha</em></h1><div className="about-content"><div className="portrait-placeholder">FS</div><div><h2>Um espaço para projetos com propósito.</h2><p>Esta página está preparada para receber a biografia, foto, redes sociais, contatos e links profissionais do autor.</p><div className="pending-list"><span>Biografia pendente</span><span>Redes sociais pendentes</span><span>Contato pendente</span></div></div></div></main> }
export default function App() { const [theme, setTheme] = useState(() => localStorage.getItem('nandostore-theme') || 'light'); const [query, setQuery] = useState(''); const [route, setRoute] = useState(window.location.hash.slice(2) || 'home'); const [selected, setSelected] = useState(null); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('nandostore-theme', theme) }, [theme]); useEffect(() => { const handleHash = () => { const nextRoute = window.location.hash.slice(2) || 'home'; const [kind, id] = nextRoute.split('/'); setRoute(nextRoute); setSelected(kind === 'app' || kind === 'ebook' ? allItems.find((item) => item.id === id) || null : null) }; handleHash(); window.addEventListener('hashchange', handleHash); return () => window.removeEventListener('hashchange', handleHash) }, []); const navigate = (next) => { setSelected(null); setQuery(''); window.location.hash = `/${next}` }; const openItem = (item) => { window.location.hash = `/${item.type}/${item.id}`; window.scrollTo({ top: 0, behavior: 'smooth' }) }; const content = selected ? <Detail item={selected} onBack={() => navigate('home')} /> : route === 'apps' ? <Catalog type="apps" onOpen={openItem} /> : route === 'ebooks' ? <Catalog type="ebooks" onOpen={openItem} /> : route === 'about' ? <About /> : <Home onOpen={openItem} onNavigate={navigate} query={query} />; return <div className="app-shell"><Header query={query} setQuery={setQuery} theme={theme} setTheme={setTheme} onNavigate={navigate} />{content}<footer><span>© {new Date().getFullYear()} NandoStore</span><span>Projetos de PB. Fernando Saldanha</span><button onClick={() => navigate('about')}>Sobre o portal ↗</button></footer></div> }
